name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

env:
  BUNDLE_PATH: vendor/bundle

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.3.2
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1

      - name: Cache Gems
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundler-cache-

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get -yqq install chromium-chromedriver
          gem install bundler --no-doc
          yarn install --frozen-lockfile
          bundle install --jobs 4 --retry 3

      - name: Compile Assets
        run: |
          bundle exec rake webpacker:compile

      - name: Run Tests & Linting
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: |
          ./bin/standardrb --no-fix
          ./bin/rake test
